/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.DoctorDirectory;
import Model.EncounterHistory;
import Model.HospitalDirectory;
import Model.PersonDirectory;
import javax.swing.JOptionPane;
import Model.PatientDirectory;
import Model.VitalSignsHistory;
/**
 *
 * @author Abhishek
 */
public class Doctor_view extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_view
     */
    PersonDirectory personDir;
    PatientDirectory patientDir;
    HospitalDirectory hospitalDir;
    DoctorDirectory docDir;
    EncounterHistory encounterDir;
    VitalSignsHistory vitalSignsDir;
    public Doctor_view(PersonDirectory personDir,PatientDirectory patientDir,HospitalDirectory hospitalDir,DoctorDirectory docDir,EncounterHistory encounterDir,VitalSignsHistory vitalSignsDir) {
        initComponents();
        this.personDir = personDir;
        this.patientDir = patientDir;
        this.hospitalDir = hospitalDir;
        this.docDir = docDir;
        this.encounterDir = encounterDir;
        this.vitalSignsDir = vitalSignsDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        patientDirBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        encounterHisBtn = new javax.swing.JButton();
        vitalSignsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientDirBtn.setText("Patient Directory");
        patientDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientDirBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        encounterHisBtn.setText("Encounter History");
        encounterHisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterHisBtnActionPerformed(evt);
            }
        });

        vitalSignsBtn.setText("View / Update Vital Signs");
        vitalSignsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalSignsBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientDirBtn)
                    .addComponent(backBtn)
                    .addComponent(encounterHisBtn)
                    .addComponent(vitalSignsBtn)
                    .addComponent(logoutBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(patientDirBtn)
                .addGap(18, 18, 18)
                .addComponent(encounterHisBtn)
                .addGap(18, 18, 18)
                .addComponent(vitalSignsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addGap(106, 106, 106))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientDirBtnActionPerformed
        // TODO add your handling code here:
        PatientDirc patientDirc = new PatientDirc(personDir, patientDir,docDir,encounterDir);
        jSplitPane1.setRightComponent(patientDirc);
    }//GEN-LAST:event_patientDirBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        // TODO add your handling code here:
        Admin_view adminView = new Admin_view(personDir,patientDir,hospitalDir,docDir,encounterDir);
        adminView.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void encounterHisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterHisBtnActionPerformed
        // TODO add your handling code here:
        EncounterHis encHistory = new EncounterHis(encounterDir, vitalSignsDir);
        jSplitPane1.setRightComponent(encHistory);
    }//GEN-LAST:event_encounterHisBtnActionPerformed

    private void vitalSignsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalSignsBtnActionPerformed
        // TODO add your handling code here:
        VitalSignPanel vitalSigns = new VitalSignPanel();
        jSplitPane1.setRightComponent(vitalSigns);
    }//GEN-LAST:event_vitalSignsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Medical_resource medRes = new Medical_resource(personDir,patientDir,hospitalDir,docDir,encounterDir,vitalSignsDir);
        medRes.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutBtnActionPerformed

    public void roleOf(String role){
        if(role.equals("admin")){
           backBtn.setVisible(true);
        } else {
            backBtn.setVisible(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Doctor_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Doctor_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Doctor_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Doctor_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Doctor_view().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton encounterHisBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton patientDirBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton vitalSignsBtn;
    // End of variables declaration//GEN-END:variables
}
