/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Doctor;
import Model.DoctorDirectory;
import Model.Patient;
import Model.Person;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class DoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorPanel
     */
    DoctorDirectory docDir;
    Person person;
    public DoctorPanel(DoctorDirectory docDir) {
        initComponents();
        detPanel.setVisible(false);
        this.docDir = docDir;
        populateDocTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        docTable = new javax.swing.JTable();
        addDoctorBtn = new javax.swing.JButton();
        detPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ageF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hosNameF = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        genderPanel = new javax.swing.JPanel();
        gender = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        updateDoctorBtn = new javax.swing.JButton();
        delDoctorBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("Doctor Directory");

        docTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Doctor Id", "Age", "Hospital Name", "Gender"
            }
        ));
        jScrollPane1.setViewportView(docTable);

        addDoctorBtn.setBackground(new java.awt.Color(204, 204, 255));
        addDoctorBtn.setText("Add a doctor");
        addDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Name :");

        jLabel3.setText("Age :");

        jLabel5.setText("Hospital Name :");

        saveBtn.setBackground(new java.awt.Color(204, 204, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(204, 204, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        gender.setText("Gender :");

        maleRadioButton.setText("Male");

        femaleRadioButton.setText("Female");

        javax.swing.GroupLayout genderPanelLayout = new javax.swing.GroupLayout(genderPanel);
        genderPanel.setLayout(genderPanelLayout);
        genderPanelLayout.setHorizontalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gender)
                .addGap(39, 39, 39)
                .addComponent(maleRadioButton)
                .addGap(18, 18, 18)
                .addComponent(femaleRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        genderPanelLayout.setVerticalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout detPanelLayout = new javax.swing.GroupLayout(detPanel);
        detPanel.setLayout(detPanelLayout);
        detPanelLayout.setHorizontalGroup(
            detPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(detPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(detPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hosNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(ageF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detPanelLayout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn))
                    .addComponent(genderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        detPanelLayout.setVerticalGroup(
            detPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ageF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hosNameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(genderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(detPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updateDoctorBtn.setBackground(new java.awt.Color(204, 204, 255));
        updateDoctorBtn.setText("Update a doctor");
        updateDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDoctorBtnActionPerformed(evt);
            }
        });

        delDoctorBtn.setBackground(new java.awt.Color(204, 204, 255));
        delDoctorBtn.setText("Delete a doctor");
        delDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDoctorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(addDoctorBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateDoctorBtn)
                        .addGap(18, 18, 18)
                        .addComponent(delDoctorBtn)))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(detPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDoctorBtn)
                    .addComponent(updateDoctorBtn)
                    .addComponent(delDoctorBtn))
                .addGap(41, 41, 41)
                .addComponent(detPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorBtnActionPerformed
        // TODO add your handling code here:
        detPanel.setVisible(true);
        updateBtn.setVisible(false);
    }//GEN-LAST:event_addDoctorBtnActionPerformed

    private void updateDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDoctorBtnActionPerformed
        // TODO add your handling code here:
        detPanel.setVisible(true);
        saveBtn.setVisible(false);
        int selectedRowIndex = docTable.getSelectedRow();
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        Doctor selectedDoc = (Doctor) model.getValueAt(selectedRowIndex, 0);
        nameF.setText(selectedDoc.getName());
        ageF.setText(String.valueOf(selectedDoc.getAge()));
        hosNameF.setText(selectedDoc.getHospitalName());
//        String gender = "";
//        if(gender.getText()="male")
//        {
//            maleRadioButton.isSelected();
//        } else if(gender.getText()="female")
//        {
//            femaleRadioButton.isSelected();
//        }
    }//GEN-LAST:event_updateDoctorBtnActionPerformed

    private void delDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDoctorBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = docTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        Doctor selectedDoctor = (Doctor) model.getValueAt(selectedRowIndex, 0);
        docDir.deletePerson(selectedDoctor);
        JOptionPane.showMessageDialog(null, "Person record deleted");
        populateDocTable();
        
    }//GEN-LAST:event_delDoctorBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String name = nameF.getText();
        int age = Integer.parseInt(ageF.getText());
        String hosName = hosNameF.getText();
        String gender = "";
        if(maleRadioButton.isSelected())
        {
            gender="male";
        } else if(femaleRadioButton.isSelected())
        {
            gender="female";
        }
        if(name == null || name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all fields");
            return;
        }
        Doctor d = new Doctor(person);
        docDir.addDoctor(d);
        d.setName(name);
        d.setAge(age);
        d.setHospitalName(hosName);
        d.setGender(gender);
        JOptionPane.showMessageDialog(null, "New person added");
        detPanel.setVisible(false);
        nameF.setText("");
        ageF.setText("");
        hosNameF.setText("");
        maleRadioButton.setText("");
        populateDocTable();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String name = nameF.getText();
        int age = Integer.parseInt(ageF.getText());
        String houseName = hosNameF.getText();
        String gender = "";
        if(maleRadioButton.isSelected())
        {
            gender="male";
        } else if(femaleRadioButton.isSelected())
        {
            gender="female";
        }
        if(name == null || name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all fields");
            return;
        }
        int selectedRowIndex = docTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        Doctor selectedDoc = (Doctor) model.getValueAt(selectedRowIndex, 0);
        selectedDoc.setName(nameF.getText());
        selectedDoc.setAge(Integer.parseInt(ageF.getText()));
        selectedDoc.setHospitalName(houseName);
        selectedDoc.setGender(gender);
        JOptionPane.showMessageDialog(null, "Person updated successfully");
        populateDocTable();
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctorBtn;
    private javax.swing.JTextField ageF;
    private javax.swing.JButton delDoctorBtn;
    private javax.swing.JPanel detPanel;
    private javax.swing.JTable docTable;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel gender;
    private javax.swing.JPanel genderPanel;
    private javax.swing.JTextField hosNameF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField nameF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateDoctorBtn;
    // End of variables declaration//GEN-END:variables

    private void populateDocTable() {
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        model.setRowCount(0);
        
        for(Doctor d : docDir.getDoctorDir()) {
            Object[] row = new Object[5];
            row[0]= d;
            row[1]= d.getDoctorId();
            row[2]= d.getAge();
            row[3]= d.getGender();
            row[4]= d.getHospitalName();
            
            model.addRow(row);
        }
    }
}
